### ISSUE TITLE
Gatekeeper Problems in Catalina

### ISSUE THREAD

**Issue by eismann23** [lpar/RedPill#4]
OSX Catalina: After every restart, I get the unknown developer prompt again, although I already clicked on open-anyway in security settings. How about signing the software so Gatekeeper will shut up? Thanks, love the saver.

**Comment by lpar** [comment]
I actually signed up for a developer account and submitted it to the app store several years ago, but it was rejected. I appealed and got rejected again. I don't plan to waste time and money trying again, sorry.
