### ISSUE TITLE
Does not run on Monterey

### ISSUE THREAD

**Issue by jafl** [lpar/RedPill#5]
After upgrading to macOS 12.0.1, I get a message saying "You cannot use the Red Pill screen saver with this version of macOS."

**Comment by lpar** [comment]
Did you recompile for 64 bit or are you using an old binary?

**Comment by jafl** [comment]
I've been using the same binary for a long time.  It worked until I upgraded to Monterey.  Can you provide a dmg for Monterey, or do I need to build from source?

**Comment by StephanieSunshine** [comment]
+1 for an M1/Monterey build please

**Comment by lpar** [comment]
Try this: https://github.com/lpar/RedPill/releases/tag/v2.1.1

**Comment by StephanieSunshine** [comment]
This works, thank you

**Comment by jafl** [comment]
It works for me, too.  Thanks!
